msrv = "1.88.0"

missing-docs-in-crate-items = true
disallowed-macros = [
    "std::column",
    "std::env",
    "std::file",
    "std::include_bytes",
    "std::include_str",
    "std::include",
    "std::line",
    "std::module_path",
    "std::option_env",
]
disallowed-names = ["alpha", "beta", "gamma", "delta"]
disallowed-types = [
    { path = "core::num::NonZeroU8", reason = "use generic `NonZero`", replacement = "core::num::NonZero" },
    { path = "core::num::NonZeroU16", reason = "use generic `NonZero`", replacement = "core::num::NonZero" },
    { path = "core::num::NonZeroU32", reason = "use generic `NonZero`", replacement = "core::num::NonZero" },
    { path = "core::num::NonZeroU64", reason = "use generic `NonZero`", replacement = "core::num::NonZero" },
    { path = "core::num::NonZeroU128", reason = "use generic `NonZero`", replacement = "core::num::NonZero" },
    { path = "core::num::NonZeroUsize", reason = "use generic `NonZero`", replacement = "core::num::NonZero" },
    { path = "core::num::NonZeroI8", reason = "use generic `NonZero`", replacement = "core::num::NonZero" },
    { path = "core::num::NonZeroI16", reason = "use generic `NonZero`", replacement = "core::num::NonZero" },
    { path = "core::num::NonZeroI32", reason = "use generic `NonZero`", replacement = "core::num::NonZero" },
    { path = "core::num::NonZeroI64", reason = "use generic `NonZero`", replacement = "core::num::NonZero" },
    { path = "core::num::NonZeroI128", reason = "use generic `NonZero`", replacement = "core::num::NonZero" },
    { path = "core::num::NonZeroIsize", reason = "use generic `NonZero`", replacement = "core::num::NonZero" },
    { path = "deranged::RangedU8", reason = "use `ru8`", replacement = "deranged::ru8" },
    { path = "deranged::RangedU16", reason = "use `ru16`", replacement = "deranged::ru16" },
    { path = "deranged::RangedU32", reason = "use `ru32`", replacement = "deranged::ru32" },
    { path = "deranged::RangedU64", reason = "use `ru64`", replacement = "deranged::ru64" },
    { path = "deranged::RangedU128", reason = "use `ru128`", replacement = "deranged::ru128" },
    { path = "deranged::RangedUsize", reason = "use `rusize`", replacement = "deranged::rusize" },
    { path = "deranged::RangedI8", reason = "use `ri8`", replacement = "deranged::ri8" },
    { path = "deranged::RangedI16", reason = "use `ri16`", replacement = "deranged::ri16" },
    { path = "deranged::RangedI32", reason = "use `ri32`", replacement = "deranged::ri32" },
    { path = "deranged::RangedI64", reason = "use `ri64`", replacement = "deranged::ri64" },
    { path = "deranged::RangedI128", reason = "use `ri128`", replacement = "deranged::ri128" },
    { path = "deranged::RangedIsize", reason = "use `risize`", replacement = "deranged::risize" },
    { path = "deranged::OptionRangedU8", reason = "use `Option_ru8`", replacement = "deranged::Option_ru8" },
    { path = "deranged::OptionRangedU16", reason = "use `Option_ru16`", replacement = "deranged::Option_ru16" },
    { path = "deranged::OptionRangedU32", reason = "use `Option_ru32`", replacement = "deranged::Option_ru32" },
    { path = "deranged::OptionRangedU64", reason = "use `Option_ru64`", replacement = "deranged::Option_ru64" },
    { path = "deranged::OptionRangedU128", reason = "use `Option_ru128`", replacement = "deranged::Option_ru128" },
    { path = "deranged::OptionRangedUsize", reason = "use `Option_rusize`", replacement = "deranged::Option_rusize" },
    { path = "deranged::OptionRangedI8", reason = "use `Option_ri8`", replacement = "deranged::Option_ri8" },
    { path = "deranged::OptionRangedI16", reason = "use `Option_ri16`", replacement = "deranged::Option_ri16" },
    { path = "deranged::OptionRangedI32", reason = "use `Option_ri32`", replacement = "deranged::Option_ri32" },
    { path = "deranged::OptionRangedI64", reason = "use `Option_ri64`", replacement = "deranged::Option_ri64" },
    { path = "deranged::OptionRangedI128", reason = "use `Option_ri128`", replacement = "deranged::Option_ri128" },
    { path = "deranged::OptionRangedIsize", reason = "use `Option_risize`", replacement = "deranged::Option_risize" },
]
matches-for-let-else = "AllTypes"
enforced-import-renames = [
    { path = "std::time::Duration", rename = "StdDuration" },
    { path = "std::time::Instant", rename = "StdInstant" },
]
semicolon-outside-block-ignore-multiline = true
