newline_style = "unix"
use_field_init_shorthand = true
use_try_shorthand = true

# Unstable features below
unstable_features = true
error_on_line_overflow = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
merge_imports = true
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
