name: Scheduled tasks

on:
  schedule:
    - cron: "0 0 * * 1,5" # midnight on Monday, Friday
  workflow_dispatch:

jobs:
  stale:
    name: Close stale PRs
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/stale@v8
        with:
          enable-statistics: false
          stale-pr-message: This pull request has not had any activity recently. It will be closed without further activity.
          days-before-stale: 30
          days-before-close: 7
          stale-pr-label: C-stale
          exempt-pr-labels: C-keep-open

  security-audit:
    name: Security audit
    runs-on: ubuntu-latest
    permissions:
      issues: write
      checks: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Audit dependencies
        uses: rustsec/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
