name: "Close stale PRs"
on:
  schedule:
    - cron: "0 0 * * 0" # midnight on Sundays

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: "This pull request has not had any activity recently. It will be closed without further activity."

          days-before-stale: 14
          days-before-close: 7

          stale-pr-label: "C-stale"
          exempt-pr-labels: "C-keep-open"
